site_name: DevToolkit Documentation
site_description: Documentation for the DevToolkit project
site_url: https://shivamojha2.github.io/DevToolkit/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest

nav:
  - Home: index.md
  - API Reference:
    - Overview: api/overview.md
    - Text Completions: api/text-completions.md
    - Chat Completions: api/chat-completions.md
    - Vision API: api/vision-api.md
    - Batch Processing: api/batch-processing.md
    - AWS Bedrock: api/bedrock.md
    - Client Factory: api/factory.md
  - Examples:
    - OpenAI Examples: examples/openai_examples.md
    - Bedrock Examples: examples/bedrock_examples.md
    - Advanced Features: examples/advanced-features.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true 