site_name: DevToolkit Documentation
site_description: Documentation for the DevToolkit project
site_url: https://shivamojha2.github.io/DevToolkit/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest

nav:
  - Home: index.md
  - API Reference:
    - Overview: api/overview.md
    - Text Completions: api/text-completions.md
    - Chat Completions: api/chat-completions.md
    - Vision API: api/vision-api.md
    - Batch Processing: api/batch-processing.md
  - Examples:
    - Basic Usage: examples/basic-usage.md
    - Advanced Features: examples/advanced-features.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - admonition
  - footnotes
  - toc:
      permalink: true 